# Generated by Django 5.1.3 on 2024-12-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tips",
            fields=[
                ("total_bill", models.FloatField(primary_key=True, serialize=False)),
                ("tip", models.FloatField()),
                ("sex", models.CharField(max_length=100)),
                ("smoker", models.CharField(max_length=100)),
                ("day", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
            ],
        ),
    ]
