# Generated by Django 5.1.3 on 2024-12-01 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tips",
            table="TIPS",
        ),
    ]
